-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 23:32:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Films` (
  `idFilms` INT NOT NULL,
  `titre` VARCHAR(70) NOT NULL,
  `description` LONGTEXT NULL,
  `image` BLOB NULL,
  `date` DATE NULL,
  `noteMoyenne` INT NULL,
  `temps` TIME NULL,
  PRIMARY KEY (`idFilms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Amis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Amis` (
  `idAmis` INT NOT NULL,
  `idUsers` INT NOT NULL,
  PRIMARY KEY (`idAmis`, `idUsers`),
  INDEX `fk_Users_has_Users_Users1_idx` (`idUsers` ASC),
  INDEX `fk_Users_has_Users_Users_idx` (`idAmis` ASC),
  CONSTRAINT `fk_Users_has_Users_Users`
    FOREIGN KEY (`idAmis`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Users_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `idCategories` INT NOT NULL,
  `nom` VARCHAR(50) NULL,
  PRIMARY KEY (`idCategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories_Films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories_Films` (
  `idCategories` INT NOT NULL,
  `idFilms` INT NOT NULL,
  PRIMARY KEY (`idCategories`, `idFilms`),
  INDEX `fk_Categories_has_Films_Films1_idx` (`idFilms` ASC),
  INDEX `fk_Categories_has_Films_Categories1_idx` (`idCategories` ASC),
  CONSTRAINT `fk_Categories_has_Films_Categories1`
    FOREIGN KEY (`idCategories`)
    REFERENCES `mydb`.`Categories` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categories_has_Films_Films1`
    FOREIGN KEY (`idFilms`)
    REFERENCES `mydb`.`Films` (`idFilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commentaires` (
  `idCommentaires` INT NOT NULL,
  `commentaire` LONGTEXT NULL,
  `date` DATETIME NULL,
  `idFilms` INT NOT NULL,
  `idUsers` INT NOT NULL,
  PRIMARY KEY (`idCommentaires`, `idFilms`, `idUsers`),
  INDEX `fk_Commentaires_Films1_idx` (`idFilms` ASC),
  INDEX `fk_Commentaires_Users1_idx` (`idUsers` ASC),
  CONSTRAINT `fk_Commentaires_Films1`
    FOREIGN KEY (`idFilms`)
    REFERENCES `mydb`.`Films` (`idFilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaires_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notes` (
  `Films_idFilms` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  `note` INT NULL,
  PRIMARY KEY (`Films_idFilms`, `Users_idUsers`),
  INDEX `fk_Films_has_Users_Users1_idx` (`Users_idUsers` ASC),
  INDEX `fk_Films_has_Users_Films1_idx` (`Films_idFilms` ASC),
  CONSTRAINT `fk_Films_has_Users_Films1`
    FOREIGN KEY (`Films_idFilms`)
    REFERENCES `mydb`.`Films` (`idFilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Films_has_Users_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Realisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Realisateurs` (
  `idRealisateurs` INT NOT NULL,
  `nom` VARCHAR(50) NULL,
  `prenom` VARCHAR(50) NULL,
  `dateNaissance` DATE NULL,
  `pays` VARCHAR(50) NULL,
  PRIMARY KEY (`idRealisateurs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Acteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acteurs` (
  `idActeurs` INT NOT NULL,
  `nom` VARCHAR(50) NULL,
  `prenom` VARCHAR(50) NULL,
  `dateNaissance` DATE NULL,
  `pays` VARCHAR(50) NULL,
  PRIMARY KEY (`idActeurs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Acteurs_Films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acteurs_Films` (
  `idRealisateurs` INT NOT NULL,
  `idFilms` INT NOT NULL,
  `nomPersonnage` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idRealisateurs`, `idFilms`),
  INDEX `fk_Acteurs_has_Films_Films1_idx` (`idFilms` ASC),
  INDEX `fk_Acteurs_has_Films_Acteurs1_idx` (`idRealisateurs` ASC),
  CONSTRAINT `fk_Acteurs_has_Films_Acteurs1`
    FOREIGN KEY (`idRealisateurs`)
    REFERENCES `mydb`.`Acteurs` (`idActeurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Acteurs_has_Films_Films1`
    FOREIGN KEY (`idFilms`)
    REFERENCES `mydb`.`Films` (`idFilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Films_Realisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Films_Realisateurs` (
  `idFilms` INT NOT NULL,
  `idRealisateurs` INT NOT NULL,
  `nombreRealisateurs` INT NOT NULL,
  PRIMARY KEY (`idFilms`, `idRealisateurs`),
  INDEX `fk_Films_has_Realisateurs_Realisateurs1_idx` (`idRealisateurs` ASC),
  INDEX `fk_Films_has_Realisateurs_Films1_idx` (`idFilms` ASC),
  CONSTRAINT `fk_Films_has_Realisateurs_Films1`
    FOREIGN KEY (`idFilms`)
    REFERENCES `mydb`.`Films` (`idFilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Films_has_Realisateurs_Realisateurs1`
    FOREIGN KEY (`idRealisateurs`)
    REFERENCES `mydb`.`Realisateurs` (`idRealisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
