-- MySQL Script generated by MySQL Workbench
-- Wed Oct 18 20:17:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `pseudo` VARCHAR(50) NOT NULL,
  `motdepasse` VARCHAR(255) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`pseudo` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`films` (
  `id` INT UNSIGNED NOT NULL,
  `titre` VARCHAR(70) NOT NULL,
  `description` LONGTEXT NULL,
  `image` BLOB NULL,
  `date` DATE NULL,
  `noteMoyenne` INT NULL,
  `temps` TIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`amis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`amis` (
  `idAmis` INT NOT NULL,
  `idUsers` INT NOT NULL,
  PRIMARY KEY (`idAmis`, `idUsers`),
  INDEX `fk_Users_has_Users_Users1_idx` (`idUsers` ASC),
  INDEX `fk_Users_has_Users_Users_idx` (`idAmis` ASC),
  CONSTRAINT `fk_Users_has_Users_Users`
    FOREIGN KEY (`idAmis`)
    REFERENCES `mydb`.`utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Users_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL COMMENT 'Mettre après des catégories par défauts',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoriesFilms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoriesFilms` (
  `idCategories` INT NOT NULL,
  `idFilms` INT NOT NULL,
  PRIMARY KEY (`idCategories`, `idFilms`),
  INDEX `fk_Categories_has_Films_Films1_idx` (`idFilms` ASC),
  INDEX `fk_Categories_has_Films_Categories1_idx` (`idCategories` ASC),
  CONSTRAINT `fk_Categories_has_Films_Categories1`
    FOREIGN KEY (`idCategories`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categories_has_Films_Films1`
    FOREIGN KEY (`idFilms`)
    REFERENCES `mydb`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commentaires` (
  `commentaire` LONGTEXT NULL,
  `date` DATETIME NULL,
  `idFilms` INT NOT NULL,
  `idUsers` INT NOT NULL,
  PRIMARY KEY (`idFilms`, `idUsers`),
  INDEX `fk_Commentaires_Films1_idx` (`idFilms` ASC),
  INDEX `fk_Commentaires_Users1_idx` (`idUsers` ASC),
  CONSTRAINT `fk_Commentaires_Films1`
    FOREIGN KEY (`idFilms`)
    REFERENCES `mydb`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaires_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notes` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notes` (
  `idFilms` INT NOT NULL,
  `idUsers` INT NOT NULL,
  `note` INT NULL,
  PRIMARY KEY (`idFilms`, `idUsers`),
  INDEX `fk_Films_has_Users_Users1_idx` (`idUsers` ASC),
  INDEX `fk_Films_has_Users_Films1_idx` (`idFilms` ASC),
  CONSTRAINT `fk_Films_has_Users_Films1`
    FOREIGN KEY (`idFilms`)
    REFERENCES `mydb`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Films_has_Users_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`realisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`realisateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `dateNaissance` DATE NOT NULL,
  `pays` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acteurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `dateNaissance` DATE NOT NULL,
  `pays` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acteursFilms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acteursFilms` (
  `idRealisateurs` INT NOT NULL,
  `idFilms` INT NOT NULL,
  `nomPersonnage` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idRealisateurs`, `idFilms`),
  INDEX `fk_Acteurs_has_Films_Films1_idx` (`idFilms` ASC),
  INDEX `fk_Acteurs_has_Films_Acteurs1_idx` (`idRealisateurs` ASC),
  CONSTRAINT `fk_Acteurs_has_Films_Acteurs1`
    FOREIGN KEY (`idRealisateurs`)
    REFERENCES `mydb`.`acteurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Acteurs_has_Films_Films1`
    FOREIGN KEY (`idFilms`)
    REFERENCES `mydb`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filmsRealisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filmsRealisateurs` (
  `idFilms` INT NOT NULL,
  `idRealisateurs` INT NOT NULL,
  `nombreRealisateurs` INT NOT NULL,
  PRIMARY KEY (`idRealisateurs`, `idFilms`),
  INDEX `fk_Films_has_Realisateurs_Realisateurs1_idx` (`idRealisateurs` ASC),
  INDEX `fk_Films_has_Realisateurs_Films1_idx` (`idFilms` ASC),
  CONSTRAINT `fk_Films_has_Realisateurs_Films1`
    FOREIGN KEY (`idFilms`)
    REFERENCES `mydb`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Films_has_Realisateurs_Realisateurs1`
    FOREIGN KEY (`idRealisateurs`)
    REFERENCES `mydb`.`realisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
